DEFAULT_DIRECT_DOMAINS = [
    "wbbasket.ru",
    "geobasket.ru",
    "vk.team",
    "sferum-dev.ru",
    "sferum.ru",
    "max.ru",
    "juicedev.ru",
    "oneme.ru",
    "rtbcdn.ru",
    "rutube.ru",
    "vigo.tech",
    "gosuslugi.ru",
    "gu-st.ru",
    "iitrust.ru",
    "megafon.ru",
    "inappstory.ru",
    "cdn-tinkoff.ru",
    "t-static.ru",
    "tbank.ru",
    "tinkoff.ru",
    "tinsurance.ru",
    "tbank-online.com",
    "vkusnoitochka.ru",
    "qsrapp.ru",
    "avito.ru",
    "avito.st",
    "yandexadexchange.net",
    "buzzoola.com",
    "fasten.ru",
    "2gis.ru",
    "2gis.com",
    "crrpay.ru",
    "dbankcloud.ru",
    "mironline.ru",
    "beeline.ru",
    "yota.ru",
    "magnit.ru",
    "mm.ru",
    "kazanexpress.ru",
    "streamerce.live",
    "goldapple.ru",
    "gid.ru",
    "mindbox.ru",
    "dodostatic.net",
    "dodois.io",
    "dodopizza.ru",
    "dodopizza.threads.im",
    "cdek.ru",
    "ad-cdek.ru",
    "uni.rest",
    "vk-portal.net",
    "moengage.com",
    "burgerkingrus.ru",
    "mos.ru",
    "tatar.ru",
    "appsflyersdk.com",
    "hh.ru",
    "shkolkovo.online",
    "mhpost.ru",
    "kompege.ru",
    "mosreg.ru",
    "chizhik.club",
]

RU_DIRECT_ZONE_RULES = [
    "regexp:^.+\\.ru$",
    "regexp:^.+\\.рф$",
    "regexp:^.+\\.xn--p1ai$",
    "domain:ru",
    "domain:xn--p1ai",
]

RU_DIRECT_DOMAIN_SUFFIXES = [
    "ru",
    "рф",
    "xn--p1ai",
]

DEFAULT_ACCESS_PROFILE_DEFINITIONS = [
    {
        "name": "Полный VPN",
        "description": "Весь трафик пользователя идет через VPN. Российские сервисы не исключаются.",
        "routing_mode": "full_tunnel",
        "direct_domains": [],
        "blocked_domains": [],
        "client_template": "vless_uri",
        "is_active": True,
    },
    {
        "name": "Российские сервисы напрямую",
        "description": "Российские домены и популярные российские сервисы идут напрямую, остальной трафик идет через VPN.",
        "routing_mode": "ru_direct",
        "direct_domains": DEFAULT_DIRECT_DOMAINS,
        "blocked_domains": [],
        "client_template": "vless_uri",
        "is_active": True,
    },
]

LEGACY_RU_DIRECT_PROFILE_NAMES = [
    "Стандартный доступ: RU direct",
    "Стандартный доступ",
]
